server:
  port: 8091
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uav_space
    username: postgres
    password: aa123456

mybatis-plus:
  type-handlers-package: com.zhd.handler

mappo:
  url: http://localhost:8000

octree:
  M: 10

motion:
  R: 0.1
  a: 70
  v: 140
  t: 0.1